version: '3.2'

services:
  crawlers:
    build: ./crawlers
    restart: always
    volumes:
      - ${PWD}/crawlers/log:/sources/log
    links:
      - elasticsearch

  elasticsearch:
    image: nshou/elasticsearch-kibana
    restart: always
    # ports:
    #   - 9200:9200
    #   - 5601:5601
    volumes:
      - ./elasticsearch:/home/elasticsearch/elasticsearch/data

